/** game-icons.net (CC BY 3.0) kategori sanatları — eksik olanlar Phosphor ikonuna düşer. */
export const CATEGORY_ART: Record<string, string> = {
  Akadlar: "/category-icons/akadlar.svg",
  "Alternatif Tıp": "/category-icons/alternatif-tip.svg",
  "Antik Diller": "/category-icons/antik-diller.svg",
  "Antik Mezopotamya": "/category-icons/antik-mezopotamya.svg",
  "Antik Mısır": "/category-icons/antik-misir.svg",
  Antropoloji: "/category-icons/antropoloji.svg",
  Arkeoloji: "/category-icons/arkeoloji.svg",
  "Aztek Uygarlığı": "/category-icons/aztek-uygarligi.svg",
  "Bayraklar & Başkentler": "/category-icons/bayraklar-baskentler.svg",
  "Bilgisayar Donanımı": "/category-icons/bilgisayar-donanimi.svg",
  "Bilim İnsanları": "/category-icons/bilim-i-nsanlari.svg",
  "Bira & İçecek Kültürü": "/category-icons/bira-i-cecek-kulturu.svg",
  Biyoçeşitlilik: "/category-icons/biyocesitlilik.svg",
  Budizm: "/category-icons/budizm.svg",
  "Canavarlar & Efsaneler": "/category-icons/canavarlar-efsaneler.svg",
  "Casuslar & İstihbarat": "/category-icons/casuslar-i-stihbarat.svg",
  Dans: "/category-icons/dans.svg",
  Dağcılık: "/category-icons/dagcilik.svg",
  Demonoloji: "/category-icons/demonoloji.svg",
  "Deniz Canlıları": "/category-icons/deniz-canlilari.svg",
  "Denizcilik Tarihi": "/category-icons/denizcilik-tarihi.svg",
  Dilbilim: "/category-icons/dilbilim.svg",
  "Dini Yapılar & Mimari": "/category-icons/dini-yapilar-mimari.svg",
  "Dinler ve İnançlar": "/category-icons/dinler-ve-i-nanclar.svg",
  "Doğal Afetler": "/category-icons/dogal-afetler.svg",
  "Doğu Felsefeleri": "/category-icons/dogu-felsefeleri.svg",
  "Dövüş Sanatları": "/category-icons/dovus-sanatlari.svg",
  "Dünya Mirasları (UNESCO)": "/category-icons/dunya-miraslari-unesco.svg",
  "Dünya Savaşları": "/category-icons/dunya-savaslari.svg",
  "Dünya Tarihi": "/category-icons/dunya-tarihi.svg",
  "Dünya Yemekleri": "/category-icons/dunya-yemekleri.svg",
  "Ekstrem Sporlar": "/category-icons/ekstrem-sporlar.svg",
  "Enerji Kaynakları": "/category-icons/enerji-kaynaklari.svg",
  Enochian: "/category-icons/enochian.svg",
  Epikürosçuluk: "/category-icons/epikurosculuk.svg",
  Etrüskler: "/category-icons/etruskler.svg",
  "Evcil Hayvanlar": "/category-icons/evcil-hayvanlar.svg",
  Fenikeliler: "/category-icons/fenikeliler.svg",
  "Finans & Ekonomi": "/category-icons/finans-ekonomi.svg",
  "Formula 1": "/category-icons/formula-1.svg",
  "Füzyon Enerjisi": "/category-icons/fuzyon-enerjisi.svg",
  Gastronomi: "/category-icons/gastronomi.svg",
  "Gelenekler & Festivaller": "/category-icons/gelenekler-festivaller.svg",
  Genetik: "/category-icons/genetik.svg",
  "Gizemler & Komplo Kültürü": "/category-icons/gizemler-komplo-kulturu.svg",
  "Gizli Cemiyetler": "/category-icons/gizli-cemiyetler.svg",
  Gnostisizm: "/category-icons/gnostisizm.svg",
  "Harry Potter": "/category-icons/harry-potter.svg",
  "Havacılık Tarihi": "/category-icons/havacilik-tarihi.svg",
  "Hayatta Kalma": "/category-icons/hayatta-kalma.svg",
  Hermetizm: "/category-icons/hermetizm.svg",
  "Hint Mitolojisi": "/category-icons/hint-mitolojisi.svg",
  "Hukuk Tarihi": "/category-icons/hukuk-tarihi.svg",
  "Japon Kültürü": "/category-icons/japon-kulturu.svg",
  "Kadim Metinler": "/category-icons/kadim-metinler.svg",
  "Kahve Kültürü": "/category-icons/kahve-kulturu.svg",
  "Kart Oyunları": "/category-icons/kart-oyunlari.svg",
  "Kayıp Uygarlıklar": "/category-icons/kayip-uygarliklar.svg",
  "Kayıp Şehirler": "/category-icons/kayip-sehirler.svg",
  "Kelt Druidleri": "/category-icons/kelt-druidleri.svg",
  "Kelt Mitolojisi": "/category-icons/kelt-mitolojisi.svg",
  "Kore Kültürü": "/category-icons/kore-kulturu.svg",
  "Kripto & Blockchain": "/category-icons/kripto-blockchain.svg",
  "Kuantum Fiziği": "/category-icons/kuantum-fizigi.svg",
  "Kutup Keşifleri": "/category-icons/kutup-kesifleri.svg",
  "Kütüphaneler Tarihi": "/category-icons/kutuphaneler-tarihi.svg",
  LOTR: "/category-icons/lotr.svg",
  "Logolar & Markalar": "/category-icons/logolar-markalar.svg",
  "Marvel & DC": "/category-icons/marvel-dc.svg",
  Masonluk: "/category-icons/masonluk.svg",
  "Maya Uygarlığı": "/category-icons/maya-uygarligi.svg",
  "Melekler & İlahi Varlıklar": "/category-icons/melekler-i-lahi-varliklar.svg",
  "Meme Kültürü": "/category-icons/meme-kulturu.svg",
  Meteoroloji: "/category-icons/meteoroloji.svg",
  "Mimari Harikalar": "/category-icons/mimari-harikalar.svg",
  Minecraft: "/category-icons/minecraft.svg",
  "Mitolojik Yaratıklar": "/category-icons/mitolojik-yaratiklar.svg",
  "Moda Tarihi": "/category-icons/moda-tarihi.svg",
  Mücevherler: "/category-icons/mucevherler.svg",
  Müzeler: "/category-icons/muzeler.svg",
  "Müzik Tarihi": "/category-icons/muzik-tarihi.svg",
  NBA: "/category-icons/nba.svg",
  Nanoteknoloji: "/category-icons/nanoteknoloji.svg",
  Nihilizm: "/category-icons/nihilizm.svg",
  "Norse Mitolojisi": "/category-icons/norse-mitolojisi.svg",
  "Numeroloji & Semboller": "/category-icons/numeroloji-semboller.svg",
  "Nükleer Enerji": "/category-icons/nukleer-enerji.svg",
  "Osmanlı Tarihi": "/category-icons/osmanli-tarihi.svg",
  "Otomobil Tarihi": "/category-icons/otomobil-tarihi.svg",
  "Oyun Karakterleri": "/category-icons/oyun-karakterleri.svg",
  "Para Tarihi": "/category-icons/para-tarihi.svg",
  "Robotik & Yapay Zeka": "/category-icons/robotik-yapay-zeka.svg",
  "Rock & Metal": "/category-icons/rock-metal.svg",
  "Rol Yapma Oyunları": "/category-icons/rol-yapma-oyunlari.svg",
  "Roma İmparatorluğu": "/category-icons/roma-i-mparatorlugu.svg",
  "Ruhlar & Hayaletler": "/category-icons/ruhlar-hayaletler.svg",
  "Rüya Yorumu": "/category-icons/ruya-yorumu.svg",
  "Saatler & Zaman": "/category-icons/saatler-zaman.svg",
  "Sanat Tarihi": "/category-icons/sanat-tarihi.svg",
  "Savaş Tarihi": "/category-icons/savas-tarihi.svg",
  "Sinema Tarihi": "/category-icons/sinema-tarihi.svg",
  "Sirk & Eğlence": "/category-icons/sirk-eglence.svg",
  Stoacılık: "/category-icons/stoacilik.svg",
  Sufizm: "/category-icons/sufizm.svg",
  "Suç Tarihi": "/category-icons/suc-tarihi.svg",
  "Sözcükler & Etimoloji": "/category-icons/sozcukler-etimoloji.svg",
  Sümerler: "/category-icons/sumerler.svg",
  Taoizm: "/category-icons/taoizm.svg",
  "Tarım & Bahçecilik": "/category-icons/tarim-bahcecilik.svg",
  "Tarım Tarihi": "/category-icons/tarim-tarihi.svg",
  "Teknoloji Tarihi": "/category-icons/teknoloji-tarihi.svg",
  "Tekstil & El Sanatları": "/category-icons/tekstil-el-sanatlari.svg",
  Tenis: "/category-icons/tenis.svg",
  "Türk Mitolojisi": "/category-icons/turk-mitolojisi.svg",
  "Tıp Tarihi": "/category-icons/tip-tarihi.svg",
  Varoluşçuluk: "/category-icons/varolusculuk.svg",
  "Volkanlar & Depremler": "/category-icons/volkanlar-depremler.svg",
  Witcher: "/category-icons/witcher.svg",
  "Yayıncılar & Streamerlar": "/category-icons/yayincilar-streamerlar.svg",
  "Yenilenebilir Enerji": "/category-icons/yenilenebilir-enerji.svg",
  "Yunan Mitolojisi": "/category-icons/yunan-mitolojisi.svg",
  "Zehirli Canlılar": "/category-icons/zehirli-canlilar.svg",
  Zerdüştlük: "/category-icons/zerdustluk.svg",
  "Çay Kültürü": "/category-icons/cay-kulturu.svg",
  "Çizgi Romanlar": "/category-icons/cizgi-romanlar.svg",
  "Ülkeler & Kültürler": "/category-icons/ulkeler-kulturler.svg",
  "İcatlar & Mucitler": "/category-icons/i-catlar-mucitler.svg",
  "İlkler & Keşifler": "/category-icons/i-lkler-kesifler.svg",
  "İnsan Vücudu": "/category-icons/i-nsan-vucudu.svg",
  Şintoizm: "/category-icons/sintoizm.svg",
};
