/**
 * Triviara ikon seti — tek kaynak.
 *
 * Eskiden her ikon ActivityApp içinde elle yazılmış tek bir <path> idi; çizgi
 * kalınlıkları/oranları tutarsızdı ve "✦ parıltı" gibi yapay zekâ ürünlerinin
 * klişe simgelerini taşıyordu. Artık Phosphor (MIT) kullanılıyor: tek tasarım
 * dili, tek çizgi ağırlığı, bundle'a yalnız kullanılan ikonlar girer (CDN yok,
 * Discord CSP'si ile uyumlu).
 *
 * Kural: küçük arayüz işaretleri `bold`, büyük/karakter ikonları (mod kartları,
 * kategori kartları) `duotone`. Parıltı/sihirli değnek/beyin/orbit gibi "AI"
 * simgeleri bu sette YOK — eklemeyin.
 */
import type { ComponentType } from "react";
import type { IconProps as PhosphorProps, IconWeight } from "@phosphor-icons/react";
import {
  Airplane,
  Alien,
  Anchor,
  ArrowClockwise,
  ArrowRight,
  ArrowUUpLeft,
  Atom,
  Axe,
  Balloon,
  Bank,
  Barbell,
  Basketball,
  BeerStein,
  Bird,
  Bomb,
  Bone,
  BookBookmark,
  BookOpenText,
  BookOpenUser,
  Books,
  Brain,
  Broadcast,
  Buildings,
  Butterfly,
  Cake,
  CalendarCheck,
  Camera,
  Campfire,
  Car,
  Cards,
  CardsThree,
  CaretDown,
  CastleTurret,
  Cat,
  ChartLineUp,
  Check,
  ChefHat,
  Church,
  Circuitry,
  Clock,
  ClockCounterClockwise,
  CloudSun,
  Clover,
  CoatHanger,
  Code,
  Coffee,
  Coins,
  Columns,
  Compass,
  Confetti,
  Cpu,
  Crosshair,
  Crown,
  Cube,
  CurrencyBtc,
  Detective,
  Diamond,
  DiceFive,
  Dna,
  DotsThreeOutline,
  Eye,
  Fan,
  FilmReel,
  FilmSlate,
  Fire,
  Fish,
  Flag,
  FlagBanner,
  FlagCheckered,
  Flask,
  FlowerLotus,
  FlyingSaucer,
  ForkKnife,
  FrameCorners,
  GameController,
  Gear,
  Ghost,
  GlobeHemisphereEast,
  GlobeHemisphereWest,
  GlobeSimple,
  GraduationCap,
  Guitar,
  HandsClapping,
  HandsPraying,
  Headset,
  Heart,
  Heartbeat,
  Horse,
  Hourglass,
  Info,
  Joystick,
  Leaf,
  Lightbulb,
  Lightning,
  Lock,
  MagicWand,
  MaskHappy,
  MathOperations,
  Medal,
  MedalMilitary,
  MicrophoneStage,
  Microscope,
  Money,
  Moon,
  Mountains,
  MusicNotes,
  MusicNotesSimple,
  NumberSquareTwo,
  Palette,
  PawPrint,
  PenNib,
  Pepper,
  Percent,
  PersonSimpleRun,
  PersonSimpleSki,
  PiggyBank,
  Planet,
  Plant,
  Popcorn,
  PuzzlePiece,
  Question,
  Quotes,
  Rainbow,
  Robot,
  Ruler,
  Sailboat,
  Scales,
  Scroll,
  ShareNetwork,
  Shield,
  ShieldCheck,
  ShieldStar,
  Shovel,
  Shuffle,
  SignOut,
  Skull,
  SlidersHorizontal,
  Smiley,
  SmileyWink,
  Snowflake,
  SoccerBall,
  SpeakerHigh,
  SpeakerSlash,
  Star,
  StarAndCrescent,
  SteeringWheel,
  Stethoscope,
  Sun,
  Sword,
  Tag,
  Target,
  TeaBag,
  Television,
  Tent,
  TestTube,
  TextAa,
  TextT,
  Timer,
  Tooth,
  Tornado,
  Tractor,
  Trademark,
  Translate,
  Tree,
  Trophy,
  TShirt,
  UserPlus,
  UsersThree,
  VinylRecord,
  Waves,
  WifiHigh,
  Wrench,
  X,
  YinYang,
} from "@phosphor-icons/react";
import { CATEGORY_ART } from "./categoryArt";

type Glyph = ComponentType<PhosphorProps>;

/** Arayüz ikonları. Anahtarlar anlamsal: "neyi gösterdiği", nasıl göründüğü değil. */
const UI_ICONS = {
  // mod kimlikleri
  cards: Cards, // Klasik: soru kartı destesi
  fuse: Bomb, // Fitil: fitili yanan bomba (8 sn)
  letters: TextAa, // Çember: harf/kelime
  coins: Coins, // Çifte Bahis: jetonlar
  teams: UsersThree, // Takım
  more: DotsThreeOutline,
  board: Columns, // Tavern Panosu: 5x5 soru panosu
  // genel
  sliders: SlidersHorizontal,
  medal: Medal,
  trophy: Trophy,
  crown: Crown,
  chevron: CaretDown,
  lock: Lock,
  check: Check,
  clock: Clock,
  close: X,
  arrow: ArrowRight,
  arrowBack: ArrowUUpLeft,
  refresh: ArrowClockwise,
  people: UsersThree,
  seat: UserPlus,
  exit: SignOut,
  globe: GlobeSimple,
  mic: MicrophoneStage,
  eye: Eye,
  flag: Flag,
  info: Info,
  calendar: CalendarCheck,
  question: Question,
  flame: Fire,
  bolt: Lightning,
  heart: Heart,
  star: Star,
  clap: HandsClapping,
  laugh: SmileyWink,
  sword: Sword,
  skull: Skull,
  scroll: Scroll, // Kelime Oyunu: parşömen
  target: Target, // Yakın Tahmin: en yakın sayı kazanır
  scale: Scales, // D/Y Blitz: doğru/yanlış terazisi
  speaker: SpeakerHigh,
  speakerOff: SpeakerSlash,
  music: MusicNotes,
  musicOff: MusicNotesSimple,
  shuffle: Shuffle,
  // Tavern kartları (joker)
  deck: CardsThree,
  percent: Percent,
  double: NumberSquareTwo,
  shield: ShieldCheck,
  snowflake: Snowflake,
} satisfies Record<string, Glyph>;

export type IconName = keyof typeof UI_ICONS;

export function Icon({
  name,
  weight = "bold",
  className = "",
}: {
  name: IconName;
  weight?: IconWeight;
  className?: string;
}) {
  const Glyph = UI_ICONS[name];
  return (
    <Glyph
      className={`qt-icon qt-ph ${name === "eye" ? "qt-icon--eye" : ""} ${className}`}
      weight={weight}
      aria-hidden="true"
    />
  );
}

/** Kategori kartı ikonları — anahtarlar oyundaki GERÇEK kategori adları. */
const CATEGORY_ICONS: Record<string, Glyph> = {
  Topluluk: UsersThree,
  Sinema: FilmSlate,
  Müzik: MusicNotes,
  Bilim: Flask,
  Biyoloji: Dna,
  Tarih: Scroll,
  Coğrafya: GlobeHemisphereWest,
  Matematik: MathOperations,
  "Genel Kültür": Lightbulb,
  Teknoloji: Cpu,
  Fizik: Atom,
  Spor: Barbell,
  Mitoloji: Sword,
  Edebiyat: BookOpenText,
  "Dizi/TV": Television,
  Sanat: Palette,
  "Video Oyunları": GameController,
  Uzay: Planet,
  Doğa: Tree,
  Kimya: TestTube,
  Felsefe: Columns,
  Yemek: ForkKnife,
  Hayvanlar: PawPrint,
  Anime: FlowerLotus,
  "Çizgi Film": Smiley,
  Otomobil: Car,
  Ekonomi: ChartLineUp,
  Sağlık: Heartbeat,
  "Popüler Kültür": Popcorn,
  İnternet: WifiHigh,
  Türkiye: StarAndCrescent,
  "Bilim Kurgu": FlyingSaucer,
  Moda: CoatHanger,
  Futbol: SoccerBall,
  Espor: Headset,
  Satranç: Horse,
  Dinozorlar: Bone,
  Deyimler: Quotes,
  Ünlüler: Star,
  Markalar: Tag,
  "Süper Kahramanlar": ShieldStar,
  Korku: Ghost,
  Polisiye: Detective,
  Diller: Translate,
  Mimari: Buildings,
  Psikoloji: Brain,
  İcatlar: Gear,
  "Yapay Zeka": Robot,
  Okyanuslar: Waves,
  "Antik Uygarlıklar": Bank,
  Bitkiler: Leaf,
  Olimpiyatlar: Medal,
  "Orta Çağ": CastleTurret,
  "İklim & Hava": CloudSun,
  İçecekler: BeerStein,
  Tiyatro: MaskHappy,
  Kaşifler: Compass,
  Denizcilik: Anchor,
  Tatlılar: Cake,
  Korsanlar: Skull,
  "Masa Oyunları": DiceFive,
  "Çizgi Roman": BookBookmark,
  Kuşlar: Bird,
  Böcekler: Butterfly,
  Baharatlar: Pepper,
  Festivaller: Confetti,
  Vikingler: Sword,
  Havacılık: Airplane,
  Bayraklar: Flag,
  Savaşlar: MedalMilitary,
  Dinler: Church,
  Fotoğrafçılık: Camera,
  Sihir: MagicWand,
  Tarım: Tractor,
  Jeoloji: Mountains,
  Oyuncaklar: PuzzlePiece,
  Osmanlı: Crown,
  "Halk Kültürü": Campfire,
  "Sosyal Medya": ShareNetwork,
  Programlama: Code,
  "Sahne Sanatları": MicrophoneStage,
  Efsaneler: Alien,
  "Kış Sporları": PersonSimpleSki,
  "Çocuk Oyunları": Balloon,

  Akadlar: CastleTurret,
  "Alternatif Tıp": Heartbeat,
  "Antik Diller": Translate,
  "Antik Mezopotamya": Crown,
  "Antik Mısır": Bank,
  Antropoloji: GraduationCap,
  Arkeoloji: Shovel,
  "Aztek Uygarlığı": Cat,
  "Bayraklar & Başkentler": FlagBanner,
  "Bilgisayar Donanımı": Circuitry,
  "Bilim İnsanları": BookOpenUser,
  "Bira & İçecek Kültürü": BeerStein,
  Biyoçeşitlilik: Tree,
  Budizm: HandsPraying,
  "Canavarlar & Efsaneler": Alien,
  "Casuslar & İstihbarat": Detective,
  Dans: PersonSimpleRun,
  Dağcılık: Mountains,
  Demonoloji: Skull,
  "Deniz Canlıları": Fish,
  "Denizcilik Tarihi": Sailboat,
  Dilbilim: TextT,
  "Dini Yapılar & Mimari": Church,
  "Dinler ve İnançlar": HandsPraying,
  "Doğal Afetler": Tornado,
  "Doğu Felsefeleri": YinYang,
  "Dövüş Sanatları": Sword,
  "Dünya Mirasları (UNESCO)": GlobeHemisphereWest,
  "Dünya Savaşları": Crosshair,
  "Dünya Tarihi": Hourglass,
  "Dünya Yemekleri": ForkKnife,
  "Ekstrem Sporlar": PersonSimpleRun,
  "Enerji Kaynakları": Lightning,
  Enochian: PenNib,
  Epikürosçuluk: Quotes,
  Etrüskler: Shield,
  "Evcil Hayvanlar": PawPrint,
  Fenikeliler: Sailboat,
  "Finans & Ekonomi": PiggyBank,
  "Formula 1": FlagCheckered,
  "Füzyon Enerjisi": Sun,
  Gastronomi: ChefHat,
  "Gelenekler & Festivaller": Confetti,
  Genetik: Dna,
  "Gizemler & Komplo Kültürü": Alien,
  "Gizli Cemiyetler": Eye,
  Gnostisizm: Star,
  "Harry Potter": Lightning,
  "Havacılık Tarihi": Airplane,
  "Hayatta Kalma": Campfire,
  Hermetizm: Flask,
  "Hint Mitolojisi": FlowerLotus,
  "Hukuk Tarihi": Scales,
  "Japon Kültürü": Fan,
  "Kadim Metinler": Books,
  "Kahve Kültürü": Coffee,
  "Kart Oyunları": Cards,
  "Kayıp Uygarlıklar": GlobeSimple,
  "Kayıp Şehirler": Buildings,
  "Kelt Druidleri": Leaf,
  "Kelt Mitolojisi": Clover,
  "Kore Kültürü": FlagBanner,
  "Kripto & Blockchain": CurrencyBtc,
  "Kuantum Fiziği": TestTube,
  "Kutup Keşifleri": Snowflake,
  "Kütüphaneler Tarihi": BookBookmark,
  LOTR: Eye,
  "Logolar & Markalar": Trademark,
  "Marvel & DC": Shield,
  Masonluk: Ruler,
  "Maya Uygarlığı": CalendarCheck,
  "Melekler & İlahi Varlıklar": Rainbow,
  "Meme Kültürü": Cat,
  Meteoroloji: Rainbow,
  "Mimari Harikalar": GlobeHemisphereEast,
  Minecraft: Cube,
  "Mitolojik Yaratıklar": Horse,
  "Moda Tarihi": TShirt,
  Mücevherler: Diamond,
  Müzeler: BookOpenText,
  "Müzik Tarihi": VinylRecord,
  NBA: Basketball,
  Nanoteknoloji: Microscope,
  Nihilizm: X,
  "Norse Mitolojisi": Axe,
  "Numeroloji & Semboller": NumberSquareTwo,
  "Nükleer Enerji": Atom,
  "Osmanlı Tarihi": Crown,
  "Otomobil Tarihi": SteeringWheel,
  "Oyun Karakterleri": Joystick,
  "Para Tarihi": Money,
  "Robotik & Yapay Zeka": Robot,
  "Rock & Metal": Guitar,
  "Rol Yapma Oyunları": DiceFive,
  "Roma İmparatorluğu": Columns,
  "Ruhlar & Hayaletler": Ghost,
  "Rüya Yorumu": Moon,
  "Saatler & Zaman": Timer,
  "Sanat Tarihi": FrameCorners,
  "Savaş Tarihi": MedalMilitary,
  "Sinema Tarihi": FilmReel,
  "Sirk & Eğlence": Tent,
  Stoacılık: Scales,
  Sufizm: MusicNotesSimple,
  "Suç Tarihi": Bomb,
  "Sözcükler & Etimoloji": PenNib,
  Sümerler: Scroll,
  Taoizm: YinYang,
  "Tarım & Bahçecilik": Plant,
  "Tarım Tarihi": Tractor,
  "Teknoloji Tarihi": ClockCounterClockwise,
  "Tekstil & El Sanatları": CoatHanger,
  Tenis: Trophy,
  "Türk Mitolojisi": StarAndCrescent,
  "Tıp Tarihi": Stethoscope,
  Varoluşçuluk: Hourglass,
  "Volkanlar & Depremler": Tornado,
  Witcher: Axe,
  "Yayıncılar & Streamerlar": Broadcast,
  "Yenilenebilir Enerji": CloudSun,
  "Yunan Mitolojisi": ShieldStar,
  "Zehirli Canlılar": Tooth,
  Zerdüştlük: Fire,
  "Çay Kültürü": TeaBag,
  "Çizgi Romanlar": Books,
  "Ülkeler & Kültürler": GlobeHemisphereEast,
  "İcatlar & Mucitler": Wrench,
  "İlkler & Keşifler": Compass,
  "İnsan Vücudu": Tooth,
  Şintoizm: Bird,
};

export function CategoryIcon({ name, weight = "duotone" }: { name: string; weight?: IconWeight }) {
  const art = CATEGORY_ART[name];
  if (art) {
    return (
      <span
        className="qt-cat-art"
        style={{ WebkitMaskImage: `url("${art}")`, maskImage: `url("${art}")` }}
        aria-hidden="true"
      />
    );
  }
  const Glyph = CATEGORY_ICONS[name] ?? Question;
  return <Glyph className="qt-icon qt-ph" weight={weight} aria-hidden="true" />;
}
