const fs=require('fs');const f='new-classic-bilim.json';const old=JSON.parse(fs.readFileSync(f)).slice(0,8);const r=[
['alien-life','Bilim kurguda Dünya dışı yaşam biçimine ne ad verilir?','What is life from outside Earth commonly called in science fiction?','Uzaylı yaşam','Alien life',['Yapay zekâ','Zaman yolculuğu','Paralel evren']],
['wormhole','Uzay-zamanda uzak noktaları bağladığı varsayılan geçit nedir?','What hypothetical passage connects distant points in spacetime?','Solucan deliği','Wormhole',['Kara delik','Yörünge','Işık yılı']],
['time-travel','Geçmişe veya geleceğe gitme fikrini anlatan kavram nedir?','What concept describes traveling to the past or future?','Zaman yolculuğu','Time travel',['Işınlanma','Klonlama','Uyku']],
['teleportation','Bir kişinin anında başka yere aktarılması fikri nedir?','What idea involves moving a person instantly to another place?','Işınlanma','Teleportation',['Kriyojenik uyku','Terraforming','Mutasyon']],
['android','İnsan görünümünde tasarlanmış robot nedir?','What is a robot designed to resemble a human called?','Android','Android',['Cyborg','Dron','Klon']],
['cyborg','Biyolojik ve mekanik parçaları birlikte taşıyan varlık nedir?','What being combines biological and mechanical parts?','Siborg','Cyborg',['Android','Robot','Hologram']],
['terraforming','Bir gezegeni yaşama uygun hâle getirme süreci nedir?','What process makes a planet suitable for life?','Dünya biçimlendirme','Terraforming',['Kriyobiyoloji','İklimleme','Yörüngeleme']],
['cryosleep','Uzun uzay yolculuklarında kullanılan derin uyku yöntemi nedir?','What deep-sleep method is used during long space voyages?','Kriyojenik uyku','Cryosleep',['Hibernasyon kapsülü','Staz alanı','Uyku ışını']],
['hologram','Üç boyutlu görünen ışık tabanlı görüntü nedir?','What light-based image appears three-dimensional?','Hologram','Hologram',['Avatar','Projeksiyon','Simülasyon']],
['dystopia','Baskıcı ve kötü düzeni anlatan gelecek toplumu türü nedir?','What type of future society is oppressive and bleak?','Distopya','Dystopia',['Ütopya','Koloni','Federasyon']],
['utopia','İdeal ve kusursuz toplum tasarımına ne ad verilir?','What is an imagined ideal society called?','Ütopya','Utopia',['Distopya','İmparatorluk','Komün']],
['multiverse','Birden çok evrenin var olduğu kuramsal yapı nedir?','What theoretical structure contains multiple universes?','Çoklu evren','Multiverse',['Tekillik','Galaksi','Zaman çizgisi']],
['parallel-universe','Bizim evrenimize alternatif olarak düşünülen evren nedir?','What is an alternative universe to our own called?','Paralel evren','Parallel universe',['Sanal dünya','Cep evren','Ayna galaksi']],
['artificial-intelligence','Makinelerin insan benzeri görevler yapmasını sağlayan alan nedir?','What field enables machines to perform human-like tasks?','Yapay zekâ','Artificial intelligence',['Robotik','Sibernetik','Biyoteknoloji']],
['machine-learning','Sistemlerin verilerden örüntü öğrenmesini sağlayan yöntem nedir?','What method lets systems learn patterns from data?','Makine öğrenmesi','Machine learning',['Şifreleme','Simülasyon','Otomasyon']],
['neural-network','Beyindeki bağlantıları örnek alan hesaplama modeli nedir?','What computing model is inspired by connections in the brain?','Sinir ağı','Neural network',['Karar ağacı','Veri tabanı','İşlemci']],
['singularity','Yapay zekânın insan zekâsını aşacağı varsayımsal eşik nedir?','What hypothetical point marks AI surpassing human intelligence?','Tekillik','Singularity',['Eşik dalgası','Büyük patlama','Kuantum sıçraması']],
['robotics','Robotların tasarım ve kullanımını inceleyen alan nedir?','What field studies the design and use of robots?','Robotik','Robotics',['Mekatronik','Otomasyon','Sibernetik']],
['cyberpunk','İleri teknoloji ve toplumsal çöküşü birleştiren tür nedir?','What genre combines advanced technology with social decay?','Siberpunk','Cyberpunk',['Steampunk','Noir','Space opera']],
['steampunk','Buhar gücüne dayalı alternatif teknoloji estetiği nedir?','What aesthetic imagines technology powered by steam?','Steampunk','Steampunk',['Cyberpunk','Dieselpunk','Solarpunk']],
['space-opera','Uzayda geçen büyük ölçekli macera türü nedir?','What genre presents grand adventures in space?','Uzay operası','Space opera',['Hard science fiction','Noir','Biopunk']],
['hard-scifi','Bilimsel ilkelere sıkı bağlı bilim kurgu türü nedir?','What science-fiction style emphasizes scientific accuracy?','Sert bilim kurgu','Hard science fiction',['Soft science fiction','Space opera','Tech noir']],
['genetic-engineering','Canlıların genlerini değiştirme teknolojisi nedir?','What technology alters the genes of living organisms?','Genetik mühendisliği','Genetic engineering',['Klonlama','Biyometri','Nanoteknoloji']],
['cloning','Genetik olarak aynı kopya canlı üretme işlemi nedir?','What process creates a genetically identical copy?','Klonlama','Cloning',['Mutasyon','Evrim','Döllenme']],
['nanotechnology','Maddenin nano ölçekte kontrolünü inceleyen alan nedir?','What field controls matter at the nanoscale?','Nanoteknoloji','Nanotechnology',['Astrofizik','Biyoloji','Mikrobiyoloji']],
['exoskeleton','İnsanın gücünü artıran dış mekanik iskelet nedir?','What external mechanical frame augments human strength?','Dış iskelet','Exoskeleton',['Zırh','Robot kol','Sibernetik kas']],
['force-field','Enerjiyle oluşturulan koruyucu bariyere ne ad verilir?','What energy-made barrier provides protection?','Enerji kalkanı','Force field',['Güç çekirdeği','Plazma duvarı','Manyetik kubbe']],
['lightsaber','Star Wars evreninin ışın tabanlı kılıcı nedir?','What is the beam-based sword in Star Wars called?','Işın kılıcı','Lightsaber',['Plazma tüfeği','Enerji mızrağı','Lazer kalkanı']],
['droid','Star Wars evreninde robotlara verilen genel ad nedir?','What general term refers to robots in Star Wars?','Droid','Droid',['Cyborg','Android','Mech']],
['replicant','Blade Runner’da insan görünümlü yapay varlığa ne denir?','What are the artificial human-like beings in Blade Runner called?','Replikant','Replicant',['Synth','Android','Clone']],
['matrix','İnsanların sanal gerçeklikte tutulduğu film evreni nedir?','What film world traps humans in virtual reality?','Matrix','The Matrix',['Simülasyon','Metaverse','Grid']],
['kaiju','Japon bilim kurgusunda dev canavar türüne ne denir?','What are giant monsters in Japanese science fiction called?','Kaiju','Kaiju',['Titan','Leviathan','Colossus']]
];const d=['kolay','orta','zor'];const add=r.map((x,i)=>({id:'bilim-kurgu-'+x[0],category:'Bilim Kurgu',text:x[1],choices:[x[3],...x[5]],correctIndex:0,difficulty:d[i%3],textEn:x[2],choicesEn:[x[4],...x[5]]}));fs.writeFileSync(f,JSON.stringify([...old,...add],null,2)+'\n');
