const fs=require('fs'); const file='new-classic-video-oyunlari.json'; const old=JSON.parse(fs.readFileSync(file)).slice(0,8);
const rows=[
['minecraft-yaratıcı','Minecraft’ın yaratıcısı olarak bilinen kişi kimdir?','Who is known as the creator of Minecraft?','Markus Persson','Markus Persson',['Hideo Kojima','Shigeru Miyamoto','Gabe Newell']],
['zelda-krallık','The Legend of Zelda serisinde prensesin adı nedir?','What is the princess’s name in The Legend of Zelda series?','Zelda','Zelda',['Samus','Peach','Aerith']],
['mario-kardeş','Mario’nun kardeşinin adı nedir?','What is Mario’s brother called?','Luigi','Luigi',['Wario','Toad','Yoshi']],
['pokemon-maskot','Pokémon serisinin en tanınan maskotu hangisidir?','Which is the best-known mascot of Pokémon?','Pikachu','Pikachu',['Eevee','Charizard','Mewtwo']],
['final-fantasy-yedinci','Final Fantasy VII’nin ana karakteri kimdir?','Who is the protagonist of Final Fantasy VII?','Cloud Strife','Cloud Strife',['Squall Leonhart','Noctis Lucis','Sora']],
['resident-evil-raccoon','Resident Evil 2 hangi kurgusal şehirde geçer?','In which fictional city does Resident Evil 2 take place?','Raccoon City','Raccoon City',['Silent Hill','Rapture','Dunwall']],
['portal-kup','Portal oyunlarında oyuncunun taşıdığı nesne nedir?','What object does the player carry in Portal?','Portal silahı','Portal gun',['Gravity gun','Plasma rifle','Scanner']],
['half-life-gordon','Half-Life serisinin kahramanı kimdir?','Who is the protagonist of the Half-Life series?','Gordon Freeman','Gordon Freeman',['Isaac Clarke','Duke Nukem','Max Payne']],
['mass-effect-shepard','Mass Effect üçlemesinin komutanı kimdir?','Who is the commander in the Mass Effect trilogy?','Shepard','Shepard',['Cortana','Marcus Fenix','Solid Snake']],
['witcher-geralt','The Witcher oyunlarının baş karakteri kimdir?','Who is the protagonist of The Witcher games?','Geralt of Rivia','Geralt of Rivia',['Ezio Auditore','Arthur Morgan','Joel Miller']],
['red-dead-arthur','Red Dead Redemption 2’de oynanan ana karakter kimdir?','Who is the main playable character in Red Dead Redemption 2?','Arthur Morgan','Arthur Morgan',['John Marston','Dutch van der Linde','Sadie Adler']],
['gta-san-andreas','Grand Theft Auto: San Andreas’ın ana karakteri kimdir?','Who is the protagonist of Grand Theft Auto: San Andreas?','Carl Johnson','Carl Johnson',['Tommy Vercetti','Niko Bellic','Michael De Santa']],
['assassins-creed-ezio','Ezio Auditore hangi serinin karakteridir?','Ezio Auditore is a character from which series?','Assassin’s Creed','Assassin’s Creed',['Far Cry','Watch Dogs','Prince of Persia']],
['far-cry-vaas','Far Cry 3’ün başlıca kötü karakteri kimdir?','Who is the main antagonist of Far Cry 3?','Vaas Montenegro','Vaas Montenegro',['Pagan Min','Joseph Seed','Handsome Jack']],
['borderlands-vault','Borderlands evreninde hazine avcılarına ne ad verilir?','What are treasure hunters called in the Borderlands universe?','Vault Hunter','Vault Hunter',['Raiders','Seekers','Pathfinders']],
['bioshock-rapture','BioShock’un ilk oyununun su altı şehri hangisidir?','What is the underwater city in the first BioShock?','Rapture','Rapture',['Columbia','City 17','Midgar']],
['fallout-vault-boy','Fallout serisinin maskotu kimdir?','Who is the mascot of the Fallout series?','Vault Boy','Vault Boy',['Pip-Boy','Nuka-Cola','Mr. Handy']],
['skyrim-dragonborn','Skyrim’de oyuncu karakterine verilen unvan nedir?','What title is given to the player character in Skyrim?','Dragonborn','Dragonborn',['Greybeard','Dovahkiin','Nerevarine']],
['elden-ring-tarnished','Elden Ring’de oyuncu karakterine ne denir?','What is the player character called in Elden Ring?','Tarnished','Tarnished',['Hunter','Ashen One','Bearer']],
['sekiro-kurt','Sekiro: Shadows Die Twice’ın kahramanının lakabı nedir?','What is the protagonist’s nickname in Sekiro: Shadows Die Twice?','Kurt','Wolf',['Owl','Hawk','Raven']],
['hades-zagreus','Hades oyununda yeraltı dünyasından kaçmaya çalışan karakter kimdir?','Who tries to escape the underworld in Hades?','Zagreus','Zagreus',['Thanatos','Orpheus','Achilles']],
['stardew-farm','Stardew Valley’de oyuncu neyi işletir?','What does the player run in Stardew Valley?','Çiftlik','Farm',['Müze','Madencilik şirketi','Liman']],
['terraria-sandbox','Terraria hangi oyun türünün örneğidir?','What type of game is Terraria?','2D sandbox','2D sandbox',['Turn-based strategy','Racing simulator','Visual novel']],
['civilization-sid','Sid Meier’s Civilization serisi neyi simüle eder?','What does Sid Meier’s Civilization simulate?','Bir uygarlığın gelişimini','The development of a civilization',['Bir futbol kulübünü','Bir uzay gemisini','Bir restoranı']],
['age-empires-microsoft','Age of Empires serisini yayımlayan şirket hangisidir?','Which company publishes the Age of Empires series?','Microsoft','Microsoft',['Nintendo','Sega','Valve']],
['starcraft-zerg','StarCraft’ta böcek benzeri uzaylı ırkın adı nedir?','What is the insect-like alien race in StarCraft called?','Zerg','Zerg',['Protoss','Terran','Kerrigan']],
['warcraft-azeroth','Warcraft evreninin ana dünyası hangisidir?','What is the main world of the Warcraft universe?','Azeroth','Azeroth',['Nirn','Runeterra','Thedas']],
['league-nexus','League of Legends maçlarında yok edilmesi gereken yapı nedir?','What structure must be destroyed in a League of Legends match?','Nexus','Nexus',['Ancient','Core','Beacon']],
['valorant-spike','VALORANT’ta saldıran takımın yerleştirdiği cihaz nedir?','What device does the attacking team plant in VALORANT?','Spike','Spike',['Beacon','Relic','Charge']],
['overwatch-tracer','Overwatch karakterlerinden hangisi zamanı geri sarabilen bir ajanıdır?','Which Overwatch character can rewind time?','Tracer','Tracer',['Mercy','D.Va','Sombra']],
['counter-strike-bomba','Counter-Strike’ta Teröristler hangi cihazı kurmaya çalışır?','What device do Terrorists try to plant in Counter-Strike?','Bomba','Bomb',['Beacon','Scanner','Relay']],
['dota-ancient','Dota 2 maçında ana hedef yapı nedir?','What is the main objective structure in a Dota 2 match?','Ancient','Ancient',['Nexus','Core','Shrine']]
]; const d=['kolay','orta','zor']; const add=rows.map((r,i)=>({id:'video-oyunlari-'+r[0],category:'Video Oyunları',text:r[1],choices:[r[3],...r[5]],correctIndex:0,difficulty:d[i%3],textEn:r[2],choicesEn:[r[4],...r[5]]})); fs.writeFileSync(file,JSON.stringify([...old,...add],null,2)+'\n');
