const fs=require('fs');
const rows=[
['G','gökcismi','Güneş’in çevresinde dolanan, kendi ışığını üretmeyen büyük gök cismi.','P','planet','A large celestial body that orbits a star and does not produce its own light.'],
['Y','yörünge','Bir gök cisminin başka bir cismin çevresinde izlediği yol.','O','orbit','The curved path followed by a body around another body.'],
['A','asteroit','Güneş’in çevresinde dolanan, gezegenlerden küçük kayalık gök cismi.','A','asteroid','A small rocky body that orbits the Sun.'],
['K','krater','Çarpma ya da volkanik etkinlikle oluşan çanak biçimli çukur.','C','crater','A bowl-shaped depression formed by an impact or volcanic activity.'],
['K','kuasar','Çok uzak bir gökadanın merkezindeki son derece parlak etkin çekirdek.','Q','quasar','An extremely bright active core at the center of a distant galaxy.'],
['P','pulsar','Düzenli aralıklarla ışınım darbesi gönderen dönen nötron yıldızı.','P','pulsar','A rotating neutron star that sends out regular pulses of radiation.'],
['F','fotometri','Gök cisimlerinin parlaklığını ölçen gözlemsel yöntem.','P','photometry','The measurement of the brightness of celestial objects.'],
['A','astronom','Gök cisimlerini ve evreni bilimsel olarak inceleyen kişi.','A','astronomer','A scientist who studies celestial objects and the universe.'],
['Z','zodyak','Güneş’in gökyüzündeki yıllık görünür yolunu çevreleyen kuşak.','Z','zodiac','The band of constellations along the Sun’s apparent yearly path.'],
['Z','zenit','Gözlemcinin tam tepesindeki gökyüzü noktası.','Z','zenith','The point in the sky directly above an observer.'],
['N','nadir','Zenitin gökyüzündeki tam karşısında bulunan nokta.','N','nadir','The point in the sky directly opposite the zenith.'],
['K','kavuşum','İki gök cisminin gökyüzünde aynı doğrultuda görünmesi.','C','conjunction','An apparent alignment of two celestial bodies in the sky.'],
['G','günberi','Bir cismin yörüngesinde Güneş’e en yakın olduğu nokta.','P','perihelion','The point in an orbit where an object is closest to the Sun.'],
['G','günöte','Bir cismin yörüngesinde Güneş’ten en uzak olduğu nokta.','A','aphelion','The point in an orbit where an object is farthest from the Sun.'],
['E','ekinoks','Gece ve gündüzün yaklaşık eşit olduğu astronomik tarih.','E','equinox','An astronomical date when day and night are nearly equal in length.'],
['G','gündönümü','Güneş’in görünür hareketinde kuzey veya güney uç noktasına ulaştığı tarih.','S','solstice','A date when the Sun reaches its northernmost or southernmost apparent position.'],
['T','tutulma','Bir gök cisminin diğerinin ışığını kısmen ya da tamamen engellemesi.','E','eclipse','An event in which one celestial body blocks another body’s light.'],
['I','ışık','Boşlukta saniyede yaklaşık 300 bin kilometre hızla yayılan elektromanyetik ışınım.','L','light','Electromagnetic radiation that travels through space at about 300,000 km/s.'],
['T','tayf','Işığın dalga boylarına ayrılmış renk ve çizgi dizisi.','S','spectrum','The range of colors or wavelengths into which light is separated.'],
['T','tayfölçer','Işığın tayfını incelemek için kullanılan aygıt.','S','spectrometer','An instrument used to analyze the spectrum of light.'],
['Ç','çekim','Kütleli cisimlerin birbirini çekmesini sağlayan temel etkileşim.','G','gravity','The fundamental interaction that attracts bodies with mass toward one another.'],
['K','kozmos','Uzay, zaman, madde ve enerjinin bütünü.','U','universe','The totality of space, time, matter, and energy.'],
['R','radyasyon','Enerjinin parçacık veya dalga biçiminde yayılması.','R','radiation','The emission and propagation of energy as particles or waves.'],
['R','roket','İtki üretmek için gazı yüksek hızla dışarı atan araç.','R','rocket','A vehicle that produces thrust by expelling gas at high speed.'],
['K','kapsül','Astronotları veya yükü taşıyan, yeniden girişe uygun uzay aracı bölümü.','C','capsule','A spacecraft compartment designed to carry crew or cargo through reentry.'],
['F','fırlatma','Bir uzay aracının taşıyıcı sistemle uzaya gönderilmesi.','L','launch','The act of sending a spacecraft into space.'],
['M','modül','Bir uzay aracının belirli bir işlev için tasarlanmış bölümü.','M','module','A section of a spacecraft designed for a specific function.'],
['İ','itki','Bir aracı ileriye doğru hareket ettiren kuvvet.','T','thrust','The force that drives a vehicle forward.'],
['İ','iniş','Uzay aracının bir gök cisminin yüzeyine ulaşması.','L','landing','The arrival of a spacecraft on the surface of a celestial body.'],
['K','kalkış','Bir aracın yüzeyden veya platformdan yükselerek ayrılması.','T','takeoff','The departure of a vehicle as it rises from a surface or platform.'],
['A','astronot','Uzay uçuşuna katılmak üzere eğitim almış kişi.','A','astronaut','A person trained to travel and work in space.'],
['U','uzay','Dünya atmosferinin ötesindeki geniş fiziksel bölge.','S','space','The vast physical region beyond Earth’s atmosphere.'],
['S','sirius','Gece göğünde görülen, Dünya’dan en parlak yıldız olarak bilinen yıldız.','S','sirius','The star known as the brightest star in Earth’s night sky.'],
['A','ateştopu','Dünya atmosferine girerken çok parlak görünen gök taşı olayı.','F','fireball','A meteoroid event that appears exceptionally bright while entering an atmosphere.'],
['H','halley','Yaklaşık 76 yılda bir görülen ünlü kısa dönemli kuyruklu yıldız.','H','halley','The famous short-period comet that returns roughly every 76 years.'],
['S','süpernova','Bir yıldızın ölümünde görülen son derece parlak patlama.','S','supernova','The extremely bright explosion associated with a star’s death.'],
['Ö','ötegezegen','Güneş Sistemi dışındaki bir yıldızın çevresinde dolanan gezegen.','E','exoplanet','A planet that orbits a star outside our Solar System.'],
['P','paralaks','Gözlem konumu değişince cismin yönünde görülen açısal kayma.','P','parallax','The apparent angular shift of an object when the observer’s position changes.'],
['T','takımyıldız','Gökyüzünde belirli bir şekil oluşturduğu düşünülen yıldız deseni.','C','constellation','A recognized pattern formed by stars as seen from Earth.'],
['K','karadelik','Çekimi ışığın bile kaçamayacağı kadar güçlü uzay bölgesi.','B','blackhole','A region of space whose gravity is so strong that even light cannot escape.']
];
const diffs=['kolay','orta','zor'];
const out=rows.map((r,i)=>({letter:r[0],clue:r[2],answer:r[1],category:'Uzay',difficulty:diffs[i%3],letterEn:r[3],clueEn:r[5],answerEn:r[4]}));
fs.writeFileSync('new-circle-uzay.json',JSON.stringify(out,null,2)+'\n');
