const fs=require('fs');
const facts=[
['mercury','Güneş’e en yakın gezegen hangisidir?','Which planet is closest to the Sun?','Merkür','Mercury',['Venüs','Mars','Dünya']],
['venus-hot','Güneş Sistemi’nin yüzey sıcaklığı en yüksek gezegeni hangisidir?','Which planet has the hottest surface in the Solar System?','Venüs','Venus',['Merkür','Mars','Jüpiter']],
['earth-third','Dünya, Güneş’e uzaklık bakımından kaçıncı gezegendir?','Which planet is Earth from the Sun by distance?','Üçüncü','Third',['İkinci','Dördüncü','Beşinci']],
['jupiter-largest','Güneş Sistemi’nin en büyük gezegeni hangisidir?','Which is the largest planet in the Solar System?','Jüpiter','Jupiter',['Satürn','Neptün','Uranüs']],
['saturn-rings','Belirgin halka sistemiyle en çok tanınan gezegen hangisidir?','Which planet is best known for its prominent ring system?','Satürn','Saturn',['Jüpiter','Uranüs','Neptün']],
['uranus-tilt','Dönme ekseni büyük ölçüde yana yatık olan gezegen hangisidir?','Which planet has an axis tilted largely on its side?','Uranüs','Uranus',['Mars','Venüs','Merkür']],
['neptune-winds','Güneş Sistemi’nde en hızlı rüzgârların ölçüldüğü gezegen hangisidir?','Which planet has the fastest measured winds in the Solar System?','Neptün','Neptune',['Mars','Jüpiter','Satürn']],
['pluto-dwarf','Plüton hangi sınıfa girer?','What class of object is Pluto?','Cüce gezegen','Dwarf planet',['Asteroit','Gaz devi','Yıldız']],
['asteroid-belt','Ana asteroit kuşağı hangi iki gezegen arasında bulunur?','Between which planets is the main asteroid belt located?','Mars ve Jüpiter','Mars and Jupiter',['Dünya ve Mars','Jüpiter ve Satürn','Venüs ve Dünya']],
['oort-cloud','Uzun dönemli kuyruklu yıldızların kaynağı olduğu düşünülen uzak bölge nedir?','What distant region is thought to supply long-period comets?','Oort Bulutu','Oort Cloud',['Kuiper Kuşağı','Asteroit Kuşağı','Manyetosfer']],
['exoplanet','Güneş Sistemi dışındaki gezegene ne ad verilir?','What is a planet outside the Solar System called?','Ötegezegen','Exoplanet',['Cüce gezegen','Uydu','Bulutsu']],
['lightyear-distance','Işık yılı hangi büyüklüğün birimidir?','What quantity is measured by a light-year?','Uzaklık','Distance',['Zaman','Kütle','Parlaklık']],
['parsec','Parsek temel olarak hangi büyüklüğü ölçer?','What does a parsec primarily measure?','Astronomik uzaklık','Astronomical distance',['Yıldız sıcaklığı','Işık şiddeti','Yörünge süresi']],
['nebula','Yıldızların doğabildiği gaz ve toz bulutuna ne denir?','What is a cloud of gas and dust where stars can form called?','Bulutsu','Nebula',['Kuyruklu yıldız','Kara delik','Uydu']],
['supernova','Büyük bir yıldızın yaşamının sonunda gerçekleşen parlak patlamaya ne denir?','What is the bright explosion at the end of a massive star’s life called?','Süpernova','Supernova',['Güneş tutulması','Kavuşum','Gün dönümü']],
['white-dwarf','Güneş benzeri bir yıldızın geride bıraktığı yoğun kalıntı nedir?','What dense remnant can a Sun-like star leave behind?','Beyaz cüce','White dwarf',['Nötron yıldızı','Kahverengi cüce','Kuyruklu yıldız']],
['neutron-star','Çoğunlukla nötronlardan oluşan aşırı yoğun yıldız kalıntısı nedir?','What is an extremely dense stellar remnant made mostly of neutrons?','Nötron yıldızı','Neutron star',['Beyaz cüce','Kırmızı dev','Bulutsu']],
['event-horizon','Kara deliğin ışığın kaçamadığı sınırına ne ad verilir?','What is the boundary beyond which light cannot escape a black hole called?','Olay ufku','Event horizon',['Kara cisim','Yörünge düzlemi','Manyetosfer']],
['red-giant','Güneş benzeri yıldızların yaşamlarının ileri evresindeki şişmiş hâli nedir?','What expanded late-life phase can a Sun-like star enter?','Kırmızı dev','Red giant',['Beyaz cüce','Ana kol','Nötron yıldızı']],
['main-sequence','Yıldızların çekirdeğinde çoğunlukla hidrojen füzyonu yaptığı dönem nedir?','What phase is when stars mainly fuse hydrogen in their cores?','Ana kol','Main sequence',['Kırmızı dev','Beyaz cüce','Süpernova']],
['solar-eclipse','Güneş tutulmasında hangi cisim Güneş ile Dünya arasına girer?','Which body moves between the Sun and Earth during a solar eclipse?','Ay','The Moon',['Mars','Venüs','Jüpiter']],
['lunar-eclipse','Ay tutulmasında Dünya hangi iki cismin arasındadır?','Between which two bodies is Earth during a lunar eclipse?','Güneş ve Ay','The Sun and the Moon',['Mars ve Ay','Güneş ve Venüs','Jüpiter ve Ay']],
['apogee','Bir uydunun yörüngesinde merkez cisme en uzak noktasına ne denir?','What is the farthest point of an orbit from its central body called?','Apoge','Apogee',['Perige','Zenit','Ekinoks']],
['perigee','Bir uydunun yörüngesinde merkez cisme en yakın noktasına ne denir?','What is the closest point of an orbit to its central body called?','Perige','Perigee',['Apoge','Günberi','Zenit']],
['equinox','Gece ve gündüzün yaklaşık eşit olduğu tarihe ne denir?','What is a date when day and night are approximately equal called?','Ekinoks','Equinox',['Gündönümü','Apoge','Kavuşum']],
['solstice','Güneş’in gökyüzünde en kuzey ya da güney konumuna ulaştığı dönüm noktasına ne denir?','What is the turning point when the Sun reaches its northernmost or southernmost position called?','Gündönümü','Solstice',['Ekinoks','Perige','Tutulma']],
['aurora','Kutup bölgelerinde görülen renkli ışık olayına ne denir?','What are the colorful lights seen near the poles called?','Kutup ışıkları','Aurora',['Zodyak ışığı','Gegenschein','Gökkuşağı']],
['solar-wind','Güneş’ten yayılan yüklü parçacık akışına ne denir?','What is the stream of charged particles flowing from the Sun called?','Güneş rüzgârı','Solar wind',['Güneş lekesi','Kozmik ışın','Güneş tutulması']],
['heliosphere','Güneş rüzgârının etkili olduğu geniş bölge nedir?','What is the broad region dominated by the solar wind called?','Güneş küresi','Heliosphere',['Manyetosfer','Kuyruk bölgesi','Oort Bulutu']],
['rover','Gezegen yüzeyinde hareket ederek veri toplayan araca ne denir?','What is a vehicle that moves across a planetary surface collecting data called?','Gezgin araç','Rover',['Yörünge aracı','İniş kapsülü','Teleskop']],
['iss','Dünya yörüngesinde ülkeler arası araştırma laboratuvarı hangisidir?','Which international research laboratory orbits Earth?','Uluslararası Uzay İstasyonu','International Space Station',['Hubble','Apollo 11','Voyager 1']],
['hubble','Dünya yörüngesinde çalışan ünlü uzay teleskobu hangisidir?','Which famous space telescope operates in Earth orbit?','Hubble','Hubble',['Kepler','Spitzer','Chandra']],
['james-webb','James Webb Uzay Teleskobu özellikle hangi ışınım bölgesini gözlemler?','Which part of the spectrum does the James Webb Space Telescope especially observe?','Kızılötesi','Infrared',['Radyo','Gama','Morötesi']],
['apollo-eleven','İnsanları Ay yüzeyine indiren ilk görev hangisidir?','Which mission first landed humans on the Moon?','Apollo 11','Apollo 11',['Apollo 8','Gemini 4','Artemis I']],
['sputnik','Dünyanın ilk yapay uydusunun adı nedir?','What was the name of the first artificial satellite?','Sputnik 1','Sputnik 1',['Explorer 1','Vostok 1','Luna 2']],
['first-human-space','Uzaya çıkan ilk insan kimdir?','Who was the first human in space?','Yuri Gagarin','Yuri Gagarin',['Neil Armstrong','Alan Shepard','John Glenn']],
['olympus-mons','Güneş Sistemi’nin bilinen en büyük yanardağı hangisidir?','What is the largest known volcano in the Solar System?','Olympus Mons','Olympus Mons',['Mauna Kea','Etna','Vesuvius']],
['valles-marineris','Mars’taki dev kanyon sisteminin adı nedir?','What is the name of the giant canyon system on Mars?','Valles Marineris','Valles Marineris',['Noctis Labyrinthus','Ares Vallis','Hellas Planitia']],
['great-red-spot','Jüpiter’in Büyük Kırmızı Leke’si nedir?','What is Jupiter’s Great Red Spot?','Dev bir fırtına','A giant storm',['Volkan','Krater','Uydu']],
['titan-moon','Satürn’ün en büyük uydusu hangisidir?','Which is Saturn’s largest moon?','Titan','Titan',['Europa','Ganymede','Triton']]
];
const diff=['kolay','orta','zor'];
const enD={
'mercury':['Venus','Mars','Earth'],'venus-hot':['Mercury','Mars','Jupiter'],'earth-third':['Second','Fourth','Fifth'],'jupiter-largest':['Saturn','Neptune','Uranus'],'saturn-rings':['Jupiter','Uranus','Neptune'],'uranus-tilt':['Mars','Venus','Mercury'],'neptune-winds':['Mars','Jupiter','Saturn'],'pluto-dwarf':['Asteroid','Gas giant','Star'],'asteroid-belt':['Earth and Mars','Jupiter and Saturn','Venus and Earth'],'oort-cloud':['Kuiper Belt','Asteroid Belt','Magnetosphere'],'exoplanet':['Dwarf planet','Moon','Nebula'],'lightyear-distance':['Time','Mass','Brightness'],'parsec':['Stellar temperature','Light intensity','Orbital period'],'nebula':['Comet','Black hole','Moon'],'supernova':['Solar eclipse','Conjunction','Solstice'],'white-dwarf':['Neutron star','Brown dwarf','Comet'],'neutron-star':['White dwarf','Red giant','Nebula'],'event-horizon':['Blackbody','Orbital plane','Magnetosphere'],'red-giant':['White dwarf','Main sequence','Neutron star'],'main-sequence':['Red giant','White dwarf','Supernova'],'solar-eclipse':['Mars','Venus','Jupiter'],'lunar-eclipse':['Mars and the Moon','The Sun and Venus','Jupiter and the Moon'],'apogee':['Perigee','Zenith','Equinox'],'perigee':['Apogee','Aphelion','Zenith'],'equinox':['Solstice','Apogee','Conjunction'],'solstice':['Equinox','Perigee','Eclipse'],'aurora':['Zodiacal light','Gegenschein','Rainbow'],'solar-wind':['Sunspot','Cosmic ray','Solar eclipse'],'heliosphere':['Magnetosphere','Tail region','Oort Cloud'],'rover':['Orbital vehicle','Landing capsule','Telescope'],'iss':['Hubble','Apollo 11','Voyager 1'],'hubble':['Kepler','Spitzer','Chandra'],'james-webb':['Radio','Gamma rays','Ultraviolet'],'apollo-eleven':['Apollo 8','Gemini 4','Artemis I'],'sputnik':['Explorer 1','Vostok 1','Luna 2'],'first-human-space':['Neil Armstrong','Alan Shepard','John Glenn'],'olympus-mons':['Mauna Kea','Etna','Vesuvius'],'valles-marineris':['Noctis Labyrinthus','Ares Vallis','Hellas Planitia'],'great-red-spot':['Volcano','Crater','Moon'],'titan-moon':['Europa','Ganymede','Triton']};
const out=facts.map((f,i)=>({id:`uzay-${f[0]}`,category:'Uzay',text:f[1],choices:[f[3],...f[5]],correctIndex:0,difficulty:diff[i%3],textEn:f[2],choicesEn:[f[4],...enD[f[0]]]}));
fs.writeFileSync('new-classic-uzay.json',JSON.stringify(out,null,2)+'\n');
